config/routes.rb
class FilterRecognizer
  def initialize(query_param)
    @query_param = query_param.to_sym
  end

  def matches?(request)
    request.params.has_key?(@query_param)
  end
end

SimpleTaskManager::Application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  post "stories" => "stories#index", :constraints => FilterRecognizer.new(:filter)

  resources :users
  resources :sessions
  resources :stories
  resources :comments

  root :to => 'stories#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
    belongs_to :user
    has_many :comments, :dependent => :destroy

    validates_presence_of :user_id, :title, :content, :state, :content
    validates_length_of :title, :maximum => 255
    validates_length_of :content, :maximum => 100
    
    scope :filter, lambda{ |params| { :conditions => params } }

    state_machine :initial => :new do
        state :new
        state :started
        state :finished
        state :accepted
        state :rejected

        event :started do
            transition :from => :new, :to => :started
        end

        event :finished do
            transition :from => :started, :to => :finished
        end

        event :accepted do
            transition :from => :finished, :to => :accepted
        end

        event :rejected do
            transition :from => :finished, :to => :rejected
        end

        event :started do
            transition :from => :rejected, :to => :started
        end
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :require_login
  before_filter :ya_acl

  # GET /stories
  # GET /stories.json
  def index
    @users = User.all
    
    if params[:filter]
        params[:filter].delete(:user_id) if params[:filter][:user_id] == ""
        params[:filter].delete(:state) if params[:filter][:state] == ""
        @stories = Story.filter(params[:filter])
    else
        @stories = Story.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(:story_id => params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
    @users = User.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
    @users = User.all
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])
    @users = User.all

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, :notice => 'Story was successfully created.' }
        format.json { render :json => @story, :status => :created, :location => @story }
      else
        format.html { render :action => "new" }
        format.json { render :json => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])
    @users = User.all

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, :notice => 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= form_for(@story) do |f|
  - if @story.errors.any?
    #error_explanation
      %h2
        = pluralize(@story.errors.count, "error")
        prohibited this story from being saved:
      %ul
        - @story.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :title, :class => "control-label"
    .controls= f.text_field :title
  .control-group
    = f.label :content, :class => "control-label"
    .controls= f.text_area :content, :size => "150x10"
  .control-group
    = f.label :user, :class => "control-label"
    .controls= f.select "user_id", options_from_collection_for_select(@users, "id", "name", @story.user_id)
  .control-group
    = f.label :state, :class => "control-label"
    .controls= f.select "state", options_for_select(@story.state_events.unshift(@story.state))
  .actions
    = f.submit nil, :class => "btn btn-primary btn-large"

app/views/stories/edit.html.haml
%fieldset
  %legend
    Editing: #{truncate(@story.title, :length => 50, :omission => '...')}
= render 'form'
= link_to 'Show', @story
|
\#{link_to 'Back', stories_path}

app/views/stories/index.html.haml
%fieldset
  %legend Listing stories
= form_for :filter, :html => {:class => "well form-inline"} do |f|
  %table
    %tr
      %td
        = f.select "user_id", options_from_collection_for_select(@users.unshift(User.new(:id=>nil, :name=>'- Select user -')), "id", "name", (params[:filter] ? params[:filter][:user_id] : nil))
      %td
        = f.select :state,                                                                                                         |
          options_for_select(Story.state_machine.states.map{|x| x.human_name}, (params[:filter] ? params[:filter][:state] : nil)), |
          {:include_blank => '- Select story state -'}                                                                             |
      %td
        = f.submit "Filter", :class => "btn"
%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th Id
    %th User
    %th Title
    %th Comments
    %th Content
    %th State
    %th
  - @stories.each_with_index do |story,i|
    %tr
      %td= link_to story.id, story
      %td= link_to story.user.name || story.user.email, story.user
      %td= link_to truncate(story.title, :length => 50, :omission => '...'), story_path(story)
      %td= story.comments.size
      %td= truncate(story.content, :length => 50, :omission => '...')
      %td= story.state
      %td
        = link_to 'Edit', edit_story_path(story)
        %br/
        = link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Story', new_story_path

app/views/stories/new.html.haml
%fieldset
  %legend New story
= render 'form'
= link_to 'Back', stories_path

app/views/stories/show.html.haml
%fieldset
  %legend= truncate(@story.title, :length => 50, :omission => '...')
%p
  %b Author:
  = @story.user.name
  \&nbsp;&lt;#{@story.user.email}&gt;
%p
  %b State:
  = @story.state
.story-content
  = @story.content
%br/
%h4 Post a comment
= form_for @comment do |f|
  %input{:name => "comment[user_id]", :type => "hidden", :value => @current_user.id}/
  %input{:name => "comment[story_id]", :type => "hidden", :value => @story.id}/
  = f.text_area :text, :size => "50x5"
  %br/
  = f.submit "Post", :class => "btn"
%table.table.table-striped.table-bordered.table-condensed
  - @comments.each do |c|
    %tr
      %td
        .clear
          .float-left
            = c.created_at.strftime("%d %b %H:%M")
            \&nbsp;by&nbsp
          .float-left
            = link_to c.user.name || c.user.email, c.user
          - if c.user == @current_user || current_user.role == "admin"
            .float-right
              = link_to 'Destroy', c, :confirm => 'Are you sure?', :method => :delete
        .clear= c.text
= link_to 'Edit', edit_story_path(@story)
|
\#{link_to 'Back', stories_path}